POST http://localhost:8080/etudiants
Content-Type: application/json

[
  {
  "nom": "Baltaci",
  "prenom": "Jonathan",
  "numEtudiant": "2150351",
  "email": "jonathanbaltaci@gmail.com"
  },
  {
    "nom": "Baltaci",
    "prenom": "Sergo",
    "numEtudiant": "45454",
    "email": "sergobaltaci@gmail.com"
  }

]

###

POST http://localhost:8080/etudiant
Content-Type: application/json


 {
    "nom": "truc",
    "prenom": "bidule",
    "numEtudiant": "455",
    "email": "trucbidule@gmail.com"

  }


###
GET http://localhost:8080/etudiants

###
GET http://localhost:8080/etudiants/624470d0b0926c08b19f9f2d